#! /bin/bash


if [[ $1 == 'qemu' ]]; then
  qemu-system-arm -M versatilepb -m 128M -nographic -s -S -kernel irq.elf &
elif [[ $1 == 'run' ]]; then
  arm-none-eabi-gdb -tui irq.elf
else
  echo "no command"
  echo $1
fi
